language: python
python: 3.6

install:
    - pip install tox

env:
  # linters and coverage
  - TOX_ENV=pep8
  - TOX_ENV=coverage

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36

    - python: 3.5
      env: TOX_ENV=py35

    - python: 3.4
      env: TOX_ENV=py34

    - python: 2.7
      env: TOX_ENV=py27

    - python: 2.6
      env: TOX_ENV=py26

script:
  - tox -e $TOX_ENV
